### ISSUE TITLE
How to run this compoent

### ISSUE THREAD

**Issue by LiuWeiMr** [afeiship/vue-photon#1]
I run this compoent but get vue error log.

[Vue warn]: Unknown custom element: <vp-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I try improt from main.js but get error log.
import VuePhoton from 'vue-photon'
Vue.use(VuePhoton)

help

**Comment by afeiship** [comment]
@LiuWeiMr 
You can refer this file:
https://github.com/afeiship/vue-photon/blob/master/public/main.js

This project is in progress, do not use in production.
But you can play with it!
